import styles from './Grain.module.css';

/**
 * Fractal noise, generated by the browser's own SVG filter and inlined as a
 * data URI. No image request, no build step, no library, and nothing to keep in
 * sync: the tile is four lines of SVG.
 *
 * `baseFrequency` sets the grain size and the low `numOctaves` keeps it fine
 * rather than cloudy. The tile is drawn once at 180px and repeated, so the
 * whole effect costs one element and one small decode.
 */
const NOISE = `<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180">
  <filter id="n" x="0" y="0" width="100%" height="100%">
    <feTurbulence type="fractalNoise" baseFrequency="0.82" numOctaves="3" stitchTiles="stitch"/>
    <feColorMatrix type="saturate" values="0"/>
  </filter>
  <rect width="180" height="180" filter="url(#n)"/>
</svg>`;

const NOISE_URI = `url("data:image/svg+xml;utf8,${encodeURIComponent(NOISE)}")`;

export function Grain() {
  return (
    <div
      className={styles.grain}
      aria-hidden="true"
      style={{ backgroundImage: NOISE_URI }}
    />
  );
}
